### PR TITLE
3D segmentation workflow

### PR DESCRIPTION
**Pull request by haesleinhuepf**
This brings everything one needs for the [famous tribolium-workflow](https://github.com/clEsperanto/pyclesperanto_prototype/blob/cca/demo/tribolium_morphometry/Tribolium%20morphometry.ipynb). I'm happy that the [plugin_function](https://github.com/clEsperanto/pyclesperanto_prototype/blob/cca/pyclesperanto_prototype/_tier0/plugin_function.py) (suggested / inspired by @jni ) decorator works well. I'm going to introduce it everywhere next.

Performance is horrible. We clearly have an issue here. :-)

This PR also brings tons for bugfixes and is quite bulky. If no one sees some dramatic isses, I will just merge soon.

### CODE REVIEW

**Comment by tlambert03** [comment]
before you go too far fixing deployment, maybe look at/merge #16, which also fixes them

**Comment by tlambert03** [comment]
regarding package data.... just use `include_package_data=True` and leave it to MANIFEST.in to declare them

**Comment by tlambert03** [comment]
I was playing with caching locally as well.  I agree it's worth considering, but I will point out that the program building step usually takes about 7 microseconds (on my computer), so while gputools did cache those programs, it's only going to save on the order of microseconds. 

second is that if you do want to cache them, we might be able to do it slightly cleaner using [`@lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache), which would both calculate & cache a program given a set of kernel name, parameters, etc...

I'll follow up on that later

**Comment by haesleinhuepf** [comment]
I was just implementing the caching strategy from clij. Happy to improve on this. I also remember that we had the suspicion that gputools-caching wouldn't work here, but I can't recall why... It had something to do with the keys in the cache....

**Comment by haesleinhuepf** [comment]
> second is that if you do want to cache them, we might be able to do it slightly cleaner using [`@lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache), which would both calculate & cache a program given a set of kernel name, parameters, etc...

Ok. 😳  This hint is GOLD! I took weeks for implementing this on the Java side. Here it's built-in 🤯 
🙏 @tlambert03

**Pull request merged**
